### ISSUE TITLE
sample data request

### ISSUE THREAD

**Issue by ganlumomo** [PinocchioYS/SuperRay#1]
Can you provide some sample data to run the example? Appreciated.

**Comment by PinocchioYS** [comment]
You can find the sample data (.graph file format) at this [repository](http://ais.informatik.uni-freiburg.de/projects/datasets/octomap/).
The .graph file can be used in the examples for the 3-D maps such as octomap and grid3D. 

For quadmap and grid2D, we added an execution that converts the 3-D scan graph into the 2-D graph in the recent version. You can use the converted 2-D scan graph as the sample data in the 2-D cases.

**Comment by ganlumomo** [comment]
Thank you so much!
