### ISSUE TITLE
Is there any example/document to demonstrate how to use the SuperRay lib to subscribe pointcloud msg and create gridmap in realtime?

### ISSUE THREAD

**Issue by xiaoyaoE** [PinocchioYS/SuperRay#2]

**Comment by PinocchioYS** [comment]
This SuperRay library is not only used in ROS, so I have used this library by linking "lib" files.

After your comments, I uploaded the example codes at this [new repository](https://github.com/PinocchioYS/realtime_occupancy_mapping) as a ROS package.

I hope the package is what you want.

**Comment by xiaoyaoE** [comment]
Thanks for your kindly help, PinocchioYS!

**Comment by PinocchioYS** [comment]
I close this issue here.
Thanks for your comment.
