### ISSUE TITLE
Unable to use superray_octomap

### ISSUE THREAD

**Issue by Ecstasy-EC** [PinocchioYS/SuperRay#3]
Hi! 

I am trying to use your fancy superray octomap on my project but it seems to have some problem on compilation. I thought it should be resulted from my wrong CMakelists. 

![image](https://user-images.githubusercontent.com/22725279/147883296-1f9875ae-813b-4f9d-ae37-4f5f8c60b93b.png)

However, same problem appeared when I add one extra line to `octomap_visualizer_node.cpp`  in your provided [visualizer](https://github.com/PinocchioYS/occupancy_map_visualizer). I inserted `octomap::CullingRegionOcTree tmp_tree(0.1);
` ahead of the main function as a global variable as following while keeping all the other things unchanged.  

![image](https://user-images.githubusercontent.com/22725279/147883330-1eda7b26-e174-4777-b680-6baa8632ea39.png)

Would you please help my to solve this problem?

Many thanks!

@PinocchioYS 

Update:
I modified the inserted line as following and the compilation passed (see below)

![image](https://user-images.githubusercontent.com/22725279/147884061-6ac4e1d1-cebe-4497-9bb3-753e50f0fe1a.png)

But a new problem here QAQ

![image](https://user-images.githubusercontent.com/22725279/147884136-e85d1184-c788-435f-9766-b624073192e6.png)

Seems like something went wrong on the symbol link.

HELP!!!

**Comment by PinocchioYS** [comment]
Hi, thanks for using our library.

When I checked the logs, it seems that the linker found the library file, but the file does not contain the implementation of some functions.

Please check the following first for solving these problems.
1) Run the binary file "example_cullingregionOcTree" in the "bin" directory.
2) Add the library path of this library: e.g.) insert a line "export LD_LIBRARY_PATH=/usr/local/lib/superray:$LD_LIBRARY_PATH" in the ".bashrc" file, when you build the SuperRay library with the "install" instruction (Ubuntu 18.04 in my case).
3) Remove the "build" directory and then re-compile this library by the "sudo make install" command.

If these instructions do not work well, could you send the CMakelist file and compiler version to me via E-mail?

**Comment by Ecstasy-EC** [comment]
@PinocchioYS 
Thanks a lot!!! 

I followed your suggestions and the examples worked. However, the ros package still failed at the same point. 

I guessed the original octomap lib might lead to a wrong link since the quadmap worked normally. Therefore I removed the original octomap package (`ros-melodic-octomap` and its relative package), leaving only superray. THEN IT WORKS!!  However, my another package using orginal octomap failed since the octomap rviz is required. 

I checked the name of the superray octomap lib and the orginal octomap lib (see below). They all have the same name. Is this the reason that the linker links to the wrong file? How can I avoid this?

![image](https://user-images.githubusercontent.com/22725279/148075872-28f24862-aee6-482b-9f55-466191e2f2bd.png)

**Comment by PinocchioYS** [comment]
I updated the original OctoMap library to the recent version and then got the error messages similar to your problem.
The key factor of this issue is to use the same lib name for OctoMap.

Changing our lib filename can be a better solution, but I need more time to handle this problem clearly.
Thus, temporarily, I updated the implementation version of the base OctoMap library from 1.9.0 to 1.9.7 (up-to-date).

Try to download our recent source code and re-build the library. Then, copy our compiled lib files to the ROS melodic lib directory.
When I tested on my environment, I used both our visualization package and the OctoMap RViz plugin without any error message.

Thank you for finding this problem!

**Comment by Ecstasy-EC** [comment]
> I updated the original OctoMap library to the recent version and then got the error messages similar to your problem. The key factor of this issue is to use the same lib name for OctoMap.
> 
> Changing our lib filename can be a better solution, but I need more time to handle this problem clearly. Thus, temporarily, I updated the implementation version of the base OctoMap library from 1.9.0 to 1.9.7 (up-to-date).
> 
> Try to download our recent source code and re-build the library. Then, copy our compiled lib files to the ROS melodic lib directory. When I tested on my environment, I used both our visualization package and the OctoMap RViz plugin without any error message.
> 
> Thank you for finding this problem!

Many thanks for your patient replies! Your solution works well on my pc and the superray octomap is really impressive! 

Should I close this issues? Or it might  be left open here so that others might find this solution if they encounter similar cases.

**Comment by PinocchioYS** [comment]
I'm glad that the problem has been solved.

It seems better to close the issue here since the issue history remains in the closed tab.
I will close this issue, thx!
